[general]
import = ["~/themes/themes/catppuccin_mocha.toml"]

[env]
LANG = "ko_KR.UTF-8"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "D2CodingLigature Nerd Font Mono"
size = 16

[font.offset]
x = 0
y = -3

[font.glyph_offset]
x = 0
y = 0
